### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fpdc#8]
Some API endpoint require to be authenticated to be used. For this the application should support OpenID Connect client and use Fedora Infrastructure instance of Ipsilon to manage it.

Conditions of Satisfaction :
- [ ] Client application can obtain an Openid token
- [ ] Client application can use an Openid token to authenticate.

**Comment by subpop** [comment]
I'd be happy to help implement this. Is there a reference application for connecting a Django application to Fedora's Ipsilon instance? I did some research into OpenID Connect libraries and [Mozilla appears to have a pretty well documented one](https://mozilla-django-oidc.readthedocs.io/en/stable/drf.html) that even integrates with DRF.

Is there a process to get client ID and client secrets?

**Comment by cverna** [comment]
@subpop great thanks for looking at this. You could start by looking at https://fedoraproject.org/wiki/Infrastructure/Authentication, we will need to define the scope we want to be added to Ipsilon.

I think at the beginning we could do with only one "admin" scope that gives the user the ability to CREATE, UPDATE and DELETE data.

You can also check how the OIDC configuration was done on another project (Flask based), [here](https://pagure.io/fedora-hubs/blob/develop/f/ansible/roles/hubs/templates/oidc_client_secrets.json) and [here](https://pagure.io/fedora-hubs/blob/develop/f/ansible/roles/hubs/tasks/main.yml#_40) 

Also I am cc'ing @puiterwijk which can help answering questions :)

**Comment by puiterwijk** [comment]
Note that it is probably not very hard to add additional scopes to the code, and having multiple scopes from the start for different tasks would make things simpler in the future (so you can require a set of scopes rather than needing "admin or <this set of scopes>").
So please start with granular scoping.
Do note that whether a specific API client is authorized to do X depends on BOTH the scopes being authorized AND the user being allowed to do something based on permissions.

**Comment by cverna** [comment]
It seems that we have a django app that uses OIDC (fedora-happiness-packets) see the [config](https://pagure.io/fedora-commops/fedora-happiness-packets/blob/master/f/happinesspackets/settings/base.py#_124)

**Comment by subpop** [comment]
> It seems that we have a django app that uses OIDC (fedora-happiness-packets) see the config

Perfect. That application is using `mozilla_django_oidc` too.

> Note that it is probably not very hard to add additional scopes to the code, and having multiple scopes from the start for different tasks would make things simpler in the future (so you can require a set of scopes rather than needing "admin or ").

This makes sense. Scopes are additive, so joining granular ones together can form larger permission sets.

> we will need to define the scope we want to be added to Ipsilon.

My initial take is to make them similar to Bodhi. Thoughts?

* create-release
* update-release
* delete-release
* create-release-type
* update-release-type
* delete-release-type

**Comment by cverna** [comment]
> My initial take is to make them similar to Bodhi. Thoughts?
> 
>     * create-release
> 
>     * update-release
> 
>     * delete-release
> 
>     * create-release-type
> 
>     * update-release-type
> 
>     * delete-release-type

I think that looks good :+1:

**Comment by subpop** [comment]
I added the [scopes to the Authentication page](https://fedoraproject.org/wiki/Infrastructure/Authentication#pdc.fedoraproject.org) and created [the ticket to add them to iddev](https://pagure.io/fedora-infrastructure/issue/7251).

**Comment by cverna** [comment]
> I added the [scopes to the Authentication page](https://fedoraproject.org/wiki/Infrastructure/Authentication#pdc.fedoraproject.org) and created [the ticket to add them to iddev](https://pagure.io/fedora-infrastructure/issue/7251).

Cool I think we should name the scope base name space named https://fpdc.fedoraproject.org/oidc/ since https://pdc.fedoraproject.org/ points to the old application that might be confusing

**Comment by subpop** [comment]
Ah good point. I renamed the wiki page's entry.

**Comment by cverna** [comment]
It looks like we might be able to test it now :smile: since [this](https://pagure.io/fedora-infrastructure/issue/7251) is now resolved

**Comment by subpop** [comment]
We still don't have a Client ID and Client Secret. Are those available somewhere for iddev?

**Comment by cverna** [comment]
> We still don't have a Client ID and Client Secret. Are those available somewhere for iddev?

Since this is for the development instance you can ask for them on the infra ticket. Once we have this working, the secrets will be managed in ansible.

**Comment by subpop** [comment]
It looks like the testing for this might need to come from only from the dev instance. To my knowledge, I don't have access to it.

**Comment by cverna** [comment]
@subpop so we have a tool that allow you to use the dynamically register `oidc-register`.  It is part of the `flask-oidc` package so we could add this to the requirements-dev.txt.

You should be able to use it like that `oidc-register --debug https://iddev.fedorainfracloud.org/ http://localhost:8000` and that will give you a client_secrets.json file.

**Comment by subpop** [comment]
Awesome. That worked like a charm.

**Comment by subpop** [comment]
It looks like that assumes a callback URL of `http://localhost:8000/oidc_callback/`, but `mozilla-django-oidc` wants a callback URL of `https://localhost:8000/oidc/callback/`. Is it possible to change the callback URL during the registration? Or is it fixed to `/oidc_callback/`?

**Comment by cverna** [comment]
> It looks like that assumes a callback URL of `http://localhost:8000/oidc_callback/`, but `mozilla-django-oidc` wants a callback URL of `https://localhost:8000/oidc/callback/`. Is it possible to change the callback URL during the registration? Or is it fixed to `/oidc_callback/`?

Would it be enough to update the callback URL in the client_secrets.json ?

**Comment by subpop** [comment]
> Would it be enough to update the callback URL in the client_secrets.json ?

No, `mozilla-django-oidc` does not read the `client_secrets.json` file. It looks for variables defined in the active Django settings module. I'll look more into whether it's possible to change the callback URL client-side. The problem is the server is expecting a callback URL of `/oidc_callback/`, but the client sends `redirect_uri=http://localhost:8000/oidc/callback/` as part of its authentication request. Is it possible to change the expected callback URL for registered clients?

**Comment by subpop** [comment]
As I suspected, adding the proper handler for `/oidc_callback` to the `urlpatterns` list lets the OAuth2 workflow run properly.

```python
    url(
        r"^oidc_callback",
        OIDCAuthenticationCallbackView.as_view(),
        name="oidc_authentication_callback",
    ),
```

It's not as clean as I would like though; is it possible to change the callback URL associated with the registered client ID?

**Comment by cverna** [comment]
> As I suspected, adding the proper handler for `/oidc_callback` to the `urlpatterns` list lets the OAuth2 workflow run properly.
> 
> ```python
>     url(
>         r"^oidc_callback",
>         OIDCAuthenticationCallbackView.as_view(),
>         name="oidc_authentication_callback",
>     ),
> ```
> 
> It's not as clean as I would like though; is it possible to change the callback URL associated with the registered client ID?

@puiterwijk  do you know if this is doable ?

**Comment by puiterwijk** [comment]
It is possible, but easier might be to just reregister with a different URL.
Alternatively, if you give me your client ID, I can modify it.

**Comment by cverna** [comment]
I have opened https://github.com/puiterwijk/flask-oidc/pull/63 to add support to the `oidc-register` cli to register with a custom URL.

**Comment by subpop** [comment]
> I have opened [puiterwijk/flask-oidc#63](https://github.com/puiterwijk/flask-oidc/pull/63) to add support to the `oidc-register` cli to register with a custom URL.

I like this solution a lot. :+1:
